### PR TITLE
Add optional mouse gestures (under interface settings).

### PR DESCRIPTION
**Pull request by fonaro**
Defalt is middle click.
I'm guessing that implementing it for older version will be similar but I can't test it.

### CODE REVIEW

**Comment by nurupo** [comment]
Thanks, I will look into it when I get time, which might take me a week or so.

**Comment by nurupo** [comment]
Take a look at [mouse-button-setting](https://github.com/nurupo/vlc-pause-click-plugin/tree/mouse-button-setting) branch. I have

 - refactored your changes
 - ported to 2.1.x (surprised it just worked, without any extra modifications required)
 - made it so the change in settings would take place immediately (without VLC restart)
 - and changed the default mouse button back to Mouse Left

My plan is to merge this PR and follow it up with my commit from the mouse-button-setting branch, but before that I want to know if you have any input on my changes made in the mouse-button-setting branch.

**Comment by fonaro** [comment]
Great. I was wondering how to make it update the settings immediately. It didn't work when the settings was under "interface".
Please take a look at my commits at my fork under the new mouse-button-setting branch with its comments. I added some minor changes.

**Comment by nurupo** [comment]
Ok, what do you think of [mouse-button-setting](https://github.com/nurupo/vlc-pause-click-plugin/tree/mouse-button-setting) now?

**Comment by nurupo** [comment]
INDEX being the last lined up the closing parentheses nicer. Didn't notice that with your tabs. Maybe I should change it back.

**Comment by nurupo** [comment]
Ok, moved the INDEX back to where you initially put it.

**Comment by nurupo** [comment]
So, how do you want me to merge all of this?

1. Just close the PR and merge my mouse-button-setting branch into the master,
2. or you will pull my mouse-button-setting branch into your master branch (GitHub will pick it up and update the PR accordingly) and then I will merge the PR

?

Either way works for me. # 1 requires no effort from your part.

**Comment by fonaro** [comment]
I pulled your mouse-button-setting branch into my master branch (option 2).
You can merge it now.

**Comment by nurupo** [comment]
Ok, cool.

I will add new Windows binaries within 24h, after I push the fix I mentioned in #5 and add Docker instructions on how to build Windows binaries.

**Comment by nurupo** [comment]
Thanks for the PR :)

**Comment by fonaro** [comment]
With pleasure

**Pull request merged**
