### PR TITLE
Cross-compile and create arm64 and universal versions for 3.0

### LINKED ISSUE #81: Mac ARM/Universal binary support request
### Is your feature request related to a problem? Please describe
Plugin doesn’t function when running arm64 binary or universal binary of VLC on an M1 Mac

### Describe the solution you'd like
Plugin would come in 3 versions: intel, arm64, universal, same as how VLC binaries are distributed

### Describe alternatives you've considered
Tried to figure out if I could compile it for myself but I could’t figure out how to get the SDK for VLC 3.0

### Additional context
In the mean time if you could update the documentation for VLC 3.0 macOS compilation that would be cool too

### PR DESCRIPTION
**Pull request by kjoonlee**
## Description

- Download a universal DMG that works on both x86_64 and arm64
- Build x86_64 version first, then build arm64 version next, then join them to get universal version
- Get ready to build x86_64 version again 

## Related issue

Allows universal builds for 3.0, closes #81

## Motivation and context

Without universal/arm64 versions then Apple Silicon users are stuck with x86_64 versions of VLC and this plugin

## How has this been tested?

This is just for 3.0. A tested version of the script has been attached in #81 #issuecomment-1116151663

I could not test on CI at all, and I have no idea how to make it work with 4.0 instead of 3.0

## Checklist

- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation
- [x] The saved settings from the old version are compatible with the settings of the new version after this change
- [x] These changes only fix a single bug/introduces a single feature (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related)
- [x] The commit messages are clear and detailed and follow [the 50/72 rule](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) (Otherwise use `git rebase -i` to modify the commit messages)
- [x] This Pull Request is ready to be reviewed, it's not a work in progress (It's perfectly okay to have WIP Pull Requests, just please indicate them as such by leaving the checkbox unchecked)

### CODE REVIEW

**Comment by nurupo** [comment]
>I could not test on CI at all

Right, Travis-CI is pretty much no more, I will need to move to GitHub Pipelines CI.

>I have no idea how to make it work with 4.0 instead of 3.0

The plugin doesn't build with VLC 4.0 as VLC 4.0 has changed API since the last time I tested it, so the plugin needs to be updated to use the new API. I actually have the changes ready on my local machine, just need to double-check and push them.

Anyway, thanks for the PR. Please note that it might be some time before I get to it, as I need to figure out the CI situation first.

**Comment by nurupo** [comment]
Huh, that's weird. I have resolved a merge conflict in your commit and force-pushed it into your PR branch. GitHub should have updated the PR with the updated commit, but instead it just closed the PR.

Anyway, I'm working on adding the universal macOS builds, so your commit should make it into the repo once I'm done.

**Comment by nurupo** [comment]
Ah, silly me, I was working in a detached HEAD, not in `kjoonlee/master`. Now it makes sense as to why that happened.

**Comment by kjoonlee** [comment]
Thank you so much!

>     * [vlc-4.0-macosx-universal.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/10227400/vlc-4.0-macosx-universal.zip)
> 
>     * [vlc-3.0-macosx-universal.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/10227401/vlc-3.0-macosx-universal.zip)

Confirmed the universal plugins for 4.0 and 3.0 both work on both Intel and Apple Silicon.

Tested on 4.0 nightly and 3.0.18 on Intel Macbook Air and M2 Macbook Air, both running macOS Ventura 13.1 (22C65).

**Comment by nurupo** [comment]
Great, thank you for testing!

**Comment by stepanjakl** [comment]
Yes

> Here you go [216cff5](https://github.com/nurupo/vlc-pause-click-plugin/commit/216cff53a77bc8e4e616dd3acdae381f801b757b), merged into master. Had to fix a few of things, as your original commit was failing on VLC 2.1 and 2.2, and didn't do universal build for 4.0.
> 
> Here are the binaries produced, if you would like to test:
> 
> * [vlc-4.0-macosx-universal.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/10227400/vlc-4.0-macosx-universal.zip)
> * [vlc-3.0-macosx-universal.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/10227401/vlc-3.0-macosx-universal.zip)
> * [vlc-2.2-macosx-intel64.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/10227402/vlc-2.2-macosx-intel64.zip)
> * [vlc-2.1-macosx-intel64.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/10227403/vlc-2.1-macosx-intel64.zip)
> 
> I'm unable to test them as I don't have a macOS system, so it would be helpful to know if at least the VLC 3.0 plugin works. Well, if you don't want to test - that's fine too, someone will eventually complain if it's not working.
> 
> I'm planning on making a new plugin release later this month, it will include the universal plugin binary for VLC 3.0.

Yes! This works on Apple Sillicone Macs, thanks a lot. This should be mentioned in the main README as it took me some time to figure it out.

**Comment by kenny1983** [comment]
> Yes! This works on Apple Sillicone Macs, thanks a lot. This should be mentioned in the main README as it took me some time to figure it out.

Agree 110%, please add this build to the releases or info about how to install it to the readme. Or both 😉

**Pull request closed without merging**
