### PR TITLE
Add Fedora install instructions

### PR DESCRIPTION
**Pull request by nurupo**
Fixes https://github.com/nurupo/vlc-pause-click-plugin/issues/87

### CODE REVIEW

**Comment by nurupo** [comment]
@Shikakiben I'm not very familiar Fedora, does this look good to you or something needs to be corrected?

Ran this in a fedora:latest (36) docker container and it built the plugin successfully.

**Comment by nurupo** [comment]
You can preview the file at https://github.com/nurupo/vlc-pause-click-plugin/blob/fedora-instructions/README.md

**Comment by Shikakiben** [comment]
@nurupo  sorry far the late answer! i juste tested whith my knew install of nobara os 37 (based on fedora 37) it work verry well. thank you

**Comment by ChildishGiant** [comment]
These instructions worked perfectly on Fedora 40, consider merging to make them more readily available 😄

**Comment by nurupo** [comment]
Thanks for testing the instructions and reminding about this PR, totally forgot about it.

I see the macOS builds are failing in this PR. Looks like the `macos-latest` GitHub Actions image changed from being amd64 to arm64. Will address this in a separate commit later.

The CI failure doesn't block this PR as the PR doesn't modify any code, so I'm merging this.

**Pull request merged**
